name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: ^2.1.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.4
  expandable: ^5.0.0
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  flutterfire_ui: ^0.4.2
  go_router: ^4.3.0
  google_sign_in: ^5.2.1
  protobuf: ^2.0.0
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  sliver_tools: ^0.2.0
  webview_flutter: ^3.0.0
  flutter_html: ^3.0.0-alpha.5
  badges: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
