name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: ^3.0.0
  badges: ^3.0.2
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^4.3.1
  expandable: ^5.0.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_html: ^3.0.0-alpha.6
  flutterfire_ui: ^0.4.2
  go_router: ^6.0.0
  google_sign_in: ^5.2.1
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  shimmer: ^2.0.0
  sliver_tools: ^0.2.0
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
