name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: ^3.3.4
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  chewie: ^1.7.5
  cloud_firestore: ^4.15.6
  expandable: ^5.0.1
  firebase_analytics: ^10.8.7
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  fl_chart: ^0.68.0
  flutter_html: ^3.0.0-beta.2
  flutter_json_view: ^1.1.3
  flutter_lints: ^3.0.1
  go_router: ^13.2.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  quiver: ^3.2.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  timelines: ^0.1.0
  url_launcher: ^6.2.5
  video_player: ^2.8.2
  webview_flutter: ^4.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
