name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: 4.2.0
  badges: 3.1.2
  cached_network_image: 3.4.1
  carousel_slider: 5.0.0
  chewie: 1.11.3
  cloud_firestore: 5.6.8
  expandable: 5.0.1
  firebase_analytics: 11.4.6
  firebase_auth: 5.5.4
  firebase_core: 3.13.1
  firebase_ui_auth: 1.16.1
  firebase_ui_oauth_google: 1.4.1
  fl_chart: 1.0.0
  flutter_html: ^3.0.0-beta.2
  flutter_json_view: 1.1.5
  flutter_lints: 5.0.0
  go_router: 15.1.2
  google_sign_in: 6.3.0
  intl: 0.20.2
  provider: 6.1.5
  quiver: 3.2.2
  shared_preferences: 2.5.3
  shimmer: 3.0.0
  sliver_tools: 0.2.12
  timelines_plus: 1.0.6
  url_launcher: 6.3.1
  uuid: 4.4.2
  video_player: 2.9.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
