name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: ^3.0.0
  badges: ^3.1.1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  cloud_firestore: ^4.9.0
  expandable: ^5.0.0
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter_html: ^3.0.0-beta.2
  flutter_lints: ^2.0.1
  flutter_scatter: ^0.2.0
  flutterfire_ui: ^0.4.3
  go_router: ^10.1.0
  google_sign_in: ^5.4.4
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sliver_tools: ^0.2.0
  url_launcher: ^6.1.10
  video_player: ^2.7.2
  webview_flutter: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
