name: espy
description: Client application for espy game library viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:

  animate_do: ^3.1.2
  badges: ^3.1.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.1
  cloud_firestore: ^4.9.3
  expandable: ^5.0.1
  firebase_analytics: ^10.5.1
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_ui_oauth_google: ^1.2.14
  firebase_ui_oauth: ^1.4.14
  fl_chart: ^0.64.0
  flutter_html: ^3.0.0-beta.2
  flutter_json_view: ^1.1.3
  flutter_lints: ^3.0.1
  go_router: ^12.1.1
  google_sign_in: ^6.1.6
  intl: ^0.18.1
  provider: ^6.0.5
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  timelines: ^0.1.0
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  webview_flutter: ^4.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
