[package]
name = "espy_server"
version = "0.1.0"
authors = ["bourdenas"]
edition = "2018"

[[bin]] 
name = "grpc_server"
path = "src/grpc_server.rs"

[[bin]] 
name = "http_server"
path = "src/http_server.rs"

[[bin]] 
name = "sync_library"
path = "src/sync_library.rs"

[dependencies]
clap = "3.0.0-beta.2"
futures = "0.3"
itertools = "0.10.0"
prost = "0.8"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.2", features = ["full"] }
tonic = "0.5"
warp = "0.3"
firestore-db-and-auth = "0.6"
async-trait = "0.1"

[build-dependencies]
tonic-build = "0.5"
